server {
    listen 80;
    server_name www.zubao-cn.xyz zubao-cn.xyz;

    root /srv/zubao/app;
    index login.html index.html;

    location / {
        try_files $uri $uri.html $uri/ /login.html;
    }
}
